// Complete Mock Fixtures for Standalone Frontend Development & Preview
// Matches the exact seeded Bella Beauty Studio schema and structure.

export const MOCK_BUSINESS = {
  id: "00000000-0000-4000-a000-000000000001",
  name: "Bella Beauty Studio",
  slug: "bella-beauty-studio",
  owner_name: "Maria Alvarez",
  industry: "Med-Spa & Beauty",
  timezone: "America/Chicago",
  phone: "(512) 555-0198",
  address: "104 E 7th St, Austin, TX 78701",
  status: "live" as const,
  deployed_at: "2026-06-01T10:00:00Z",
  monthly_recovered_cents: 482000,
  created_at: "2026-06-01T10:00:00Z",
  updated_at: "2026-06-15T12:00:00Z",
};

export const MOCK_PROFILE = {
  id: "00000000-0000-0000-0000-000000000001",
  full_name: "Maria Alvarez",
  avatar_url: null,
  business_id: MOCK_BUSINESS.id,
  business: MOCK_BUSINESS,
  created_at: "2026-06-01T10:00:00Z",
  updated_at: "2026-06-15T12:00:00Z",
};

export const MOCK_ENGINES = [
  {
    id: "eng-1",
    business_id: MOCK_BUSINESS.id,
    engine_type: "missed_call" as const,
    status: "live" as const,
    health: "healthy" as const,
    recovered_cents_mtd: 184000,
    opportunities_in_motion: 6,
    last_outcome_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    notes: "Peak volume 11am-2pm handled with 98% 60-second response rate.",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "eng-2",
    business_id: MOCK_BUSINESS.id,
    engine_type: "after_hours" as const,
    status: "live" as const,
    health: "healthy" as const,
    recovered_cents_mtd: 125000,
    opportunities_in_motion: 4,
    last_outcome_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    notes: "Overnight inquiries captured and scheduled into morning openings.",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "eng-3",
    business_id: MOCK_BUSINESS.id,
    engine_type: "reactivation" as const,
    status: "live" as const,
    health: "healthy" as const,
    recovered_cents_mtd: 98000,
    opportunities_in_motion: 8,
    last_outcome_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    notes: "60-day lapsed client campaign delivering 22% rebooking rate.",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "eng-4",
    business_id: MOCK_BUSINESS.id,
    engine_type: "no_show" as const,
    status: "live" as const,
    health: "healthy" as const,
    recovered_cents_mtd: 45000,
    opportunities_in_motion: 3,
    last_outcome_at: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    notes: "2-step SMS confirmation reduced chair no-shows to under 1.5%.",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "eng-5",
    business_id: MOCK_BUSINESS.id,
    engine_type: "reputation" as const,
    status: "live" as const,
    health: "healthy" as const,
    recovered_cents_mtd: 30000,
    opportunities_in_motion: 2,
    last_outcome_at: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    notes: "14 new 5-star Google reviews generated this cycle.",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-15T12:00:00Z",
  },
];

export const MOCK_ATTENTION_ITEMS = [
  {
    id: "att-1",
    business_id: MOCK_BUSINESS.id,
    title: "Confirm slot change for Jessica Vance",
    description: "Jessica requested moving her HydraFacial from 3:00 PM to 4:30 PM today.",
    cta_label: "Approve change",
    severity: "action" as const,
    resolved_at: null,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: "att-2",
    business_id: MOCK_BUSINESS.id,
    title: "Review custom note for VIP client Liam O'Connor",
    description: "Liam asked if stylist Elena has availability for a consultation this Friday.",
    cta_label: "View inquiry",
    severity: "info" as const,
    resolved_at: null,
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "act-1",
    business_id: MOCK_BUSINESS.id,
    kind: "recovered_booking" as const,
    engine_type: "missed_call" as const,
    headline: "Recovered booking for Sarah Jenkins (HydraFacial Deluxe)",
    detail: "Missed call followed up via SMS within 42 seconds. Booking confirmed for tomorrow at 2:00 PM.",
    amount_cents: 18500,
    occurred_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: "act-2",
    business_id: MOCK_BUSINESS.id,
    kind: "customer_returned" as const,
    engine_type: "reactivation" as const,
    headline: "Lapsed customer returned: Marcus Thorne booked Full Highlight",
    detail: "Last visit was 78 days ago. Personalized return invitation converted.",
    amount_cents: 22000,
    occurred_at: new Date(Date.now() - 52 * 60 * 1000).toISOString(),
  },
  {
    id: "act-3",
    business_id: MOCK_BUSINESS.id,
    kind: "recovered_booking" as const,
    engine_type: "after_hours" as const,
    headline: "Overnight inquiry booked for Emily Zhang (Laser Therapy)",
    detail: "Inquiry received at 11:20 PM. Booked directly into open slot for Thursday 10:00 AM.",
    amount_cents: 31000,
    occurred_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  {
    id: "act-4",
    business_id: MOCK_BUSINESS.id,
    kind: "appointment_confirmed" as const,
    engine_type: "no_show" as const,
    headline: "Appointment confirmed: Chloe Bennett for 4:00 PM today",
    detail: "SMS confirmation acknowledged in 3 minutes.",
    amount_cents: 9500,
    occurred_at: new Date(Date.now() - 170 * 60 * 1000).toISOString(),
  },
  {
    id: "act-5",
    business_id: MOCK_BUSINESS.id,
    kind: "review_generated" as const,
    engine_type: "reputation" as const,
    headline: "New 5-star Google review posted by Hannah Miller",
    detail: "'Absolutely best service in Austin! The team always takes such great care of me.'",
    amount_cents: null,
    occurred_at: new Date(Date.now() - 280 * 60 * 1000).toISOString(),
  },
  {
    id: "act-6",
    business_id: MOCK_BUSINESS.id,
    kind: "recovered_booking" as const,
    engine_type: "missed_call" as const,
    headline: "Recovered booking for David Kim (Signature Blowout)",
    detail: "Instant callback converted inbound inquiry into confirmed seat.",
    amount_cents: 8500,
    occurred_at: new Date(Date.now() - 340 * 60 * 1000).toISOString(),
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: "cust-1",
    business_id: MOCK_BUSINESS.id,
    full_name: "Sarah Jenkins",
    email: "sarah.j@example.com",
    phone: "(512) 555-0142",
    status: "active" as const,
    lifetime_value_cents: 142000,
    revenue_opportunity_cents: 18500,
    last_visit_at: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    last_interaction_summary: "Booked HydraFacial Deluxe via Missed Call Recovery.",
  },
  {
    id: "cust-2",
    business_id: MOCK_BUSINESS.id,
    full_name: "Marcus Thorne",
    email: "marcus.t@example.com",
    phone: "(512) 555-0188",
    status: "vip" as const,
    lifetime_value_cents: 385000,
    revenue_opportunity_cents: 22000,
    last_visit_at: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    last_interaction_summary: "Reactivated after 78 days. Full Highlight booked.",
  },
  {
    id: "cust-3",
    business_id: MOCK_BUSINESS.id,
    full_name: "Emily Zhang",
    email: "emily.z@example.com",
    phone: "(512) 555-0177",
    status: "new" as const,
    lifetime_value_cents: 31000,
    revenue_opportunity_cents: 31000,
    last_visit_at: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    last_interaction_summary: "After-hours booking confirmed for Laser Therapy.",
  },
  {
    id: "cust-4",
    business_id: MOCK_BUSINESS.id,
    full_name: "Jessica Vance",
    email: "jessica.v@example.com",
    phone: "(512) 555-0112",
    status: "active" as const,
    lifetime_value_cents: 98000,
    revenue_opportunity_cents: 14000,
    last_visit_at: new Date(Date.now() - 8 * 86400 * 1000).toISOString(),
    last_interaction_summary: "Slot adjustment requested for today.",
  },
  {
    id: "cust-5",
    business_id: MOCK_BUSINESS.id,
    full_name: "Rachel Moore",
    email: "rachel.m@example.com",
    phone: "(512) 555-0199",
    status: "lapsed" as const,
    lifetime_value_cents: 215000,
    revenue_opportunity_cents: 17500,
    last_visit_at: new Date(Date.now() - 64 * 86400 * 1000).toISOString(),
    last_interaction_summary: "Sent reactivation offer with 15% return incentive.",
  },
  {
    id: "cust-6",
    business_id: MOCK_BUSINESS.id,
    full_name: "Liam O'Connor",
    email: "liam.oc@example.com",
    phone: "(512) 555-0133",
    status: "vip" as const,
    lifetime_value_cents: 490000,
    revenue_opportunity_cents: 25000,
    last_visit_at: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    last_interaction_summary: "Inquired regarding stylist Elena's availability.",
  },
];

export const MOCK_REPORTS = [
  {
    id: "rep-1",
    business_id: MOCK_BUSINESS.id,
    period_type: "weekly" as const,
    period_start: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    recovered_cents: 124000,
    bookings_recovered: 11,
    customers_returned: 4,
    reviews_generated: 5,
    summary_markdown: "Solid week with strong momentum on Missed Call Recovery and customer reactivations. 11 bookings were rescued across the floor.",
  },
  {
    id: "rep-2",
    business_id: MOCK_BUSINESS.id,
    period_type: "weekly" as const,
    period_start: new Date(Date.now() - 14 * 86400 * 1000).toISOString(),
    period_end: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
    recovered_cents: 118000,
    bookings_recovered: 10,
    customers_returned: 3,
    reviews_generated: 4,
    summary_markdown: "After-hours booking engine saw increased capture over the weekend. All 3 lapsed customer invites converted into high-ticket appointments.",
  },
  {
    id: "rep-3",
    business_id: MOCK_BUSINESS.id,
    period_type: "monthly" as const,
    period_start: new Date(Date.now() - 30 * 86400 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    recovered_cents: 482000,
    bookings_recovered: 46,
    customers_returned: 18,
    reviews_generated: 20,
    summary_markdown: "Monthly milestone reached: $4,820 recovered quietly in the background without staff manual effort. Overall floor utilization up 14%.",
  },
];

export const MOCK_LOCATIONS = [
  {
    id: "loc-1",
    business_id: MOCK_BUSINESS.id,
    name: "Downtown Austin (Flagship)",
    address: "104 E 7th St, Austin, TX 78701",
    is_primary: true,
  },
  {
    id: "loc-2",
    business_id: MOCK_BUSINESS.id,
    name: "Domain Northside",
    address: "11700 Domain Blvd #110, Austin, TX 78758",
    is_primary: false,
  },
];

export const MOCK_INTEGRATIONS = [
  {
    id: "int-1",
    business_id: MOCK_BUSINESS.id,
    kind: "crm" as const,
    provider: "Boulevard POS",
    status: "connected" as const,
    connected_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "int-2",
    business_id: MOCK_BUSINESS.id,
    kind: "phone" as const,
    provider: "Twilio Voice & SMS",
    status: "connected" as const,
    connected_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "int-3",
    business_id: MOCK_BUSINESS.id,
    kind: "reviews" as const,
    provider: "Google Business Profile",
    status: "connected" as const,
    connected_at: "2026-06-02T14:00:00Z",
  },
  {
    id: "int-4",
    business_id: MOCK_BUSINESS.id,
    kind: "calendar" as const,
    provider: "Google Calendar Sync",
    status: "connected" as const,
    connected_at: "2026-06-02T14:00:00Z",
  },
];
